# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44809af24dd9123ba2cad1fc5b32e808f0ab379820fbebbf524d48e28b05a974a12c9accc63a3d9b3f03638d6f10c1bab9aaaec139792df53717a27d187f47e5

test:
  secret_key_base: 426cc7a13fdfa9bc2a6852e69167fee68f1ec07dbd2f51edf0543e650755576361369d92f5257383bbabc76ee99457fd93110c3c0df8819b9fff39e0ab6214d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
